2017-08-18 11:46:06  task  INFO       rule: txt\3_fields_process_mrn\f_l_middle.txt; pairs number: 20986
2017-08-18 11:46:18  task  INFO       rule: txt\3_fields_process_mrn\f_l_ssn.txt; pairs number: 32612
2017-08-18 11:46:58  task  INFO       rule: txt\3_fields_process_mrn\f_dob_ssn.txt; pairs number: 36286
2017-08-18 11:47:02  task  INFO       rule: txt\3_fields_process_mrn\f_l_dob.txt; pairs number: 74476
2017-08-18 11:47:25  task  INFO       rule: txt\3_fields_process_mrn\f_l_email.txt; pairs number: 64210
2017-08-18 11:47:29  task  INFO       rule: txt\3_fields_process_mrn\f_dob_addr.txt; pairs number: 24048
2017-08-18 11:47:39  task  INFO       rule: txt\3_fields_process_mrn\f_l_addr.txt; pairs number: 24920
2017-08-18 11:47:39  task  INFO       rule: txt\3_fields_process_mrn\f_l_phone.txt; pairs number: 44294
2017-08-18 11:47:55  task  INFO       rule: txt\3_fields_process_mrn\f_ssn_middle.txt; pairs number: 6040
2017-08-18 11:48:00  task  INFO       rule: txt\3_fields_process_mrn\f_dob_middle.txt; pairs number: 16498
2017-08-18 11:48:00  task  INFO       rule: txt\3_fields_process_mrn\f_ssn_email.txt; pairs number: 0
2017-08-18 11:48:10  task  INFO       rule: txt\3_fields_process_mrn\f_ssn_addr.txt; pairs number: 11060
2017-08-18 11:48:22  task  INFO       rule: txt\3_fields_process_mrn\f_addr_middle.txt; pairs number: 6228
2017-08-18 11:48:23  task  INFO       rule: txt\3_fields_process_mrn\f_ssn_phone.txt; pairs number: 7348
2017-08-18 11:48:33  task  INFO       rule: txt\3_fields_process_mrn\f_addr_email.txt; pairs number: 52
2017-08-18 11:48:39  task  INFO       rule: txt\3_fields_process_mrn\f_email_phone.txt; pairs number: 0
2017-08-18 11:48:45  task  INFO       rule: txt\3_fields_process_mrn\f_addr_phone.txt; pairs number: 13446
2017-08-18 11:49:05  task  INFO       rule: txt\3_fields_process_mrn\f_middle_phone.txt; pairs number: 9222
2017-08-18 11:49:18  task  INFO       rule: txt\3_fields_process_mrn\l_dob_ssn.txt; pairs number: 33216
2017-08-18 11:49:19  task  INFO       rule: txt\3_fields_process_mrn\f_dob_phone.txt; pairs number: 42308
2017-08-18 11:49:30  task  INFO       rule: txt\3_fields_process_mrn\l_dob_middle.txt; pairs number: 17870
2017-08-18 11:49:41  task  INFO       rule: txt\3_fields_process_mrn\l_ssn_addr.txt; pairs number: 11146
2017-08-18 11:49:52  task  INFO       rule: txt\3_fields_process_mrn\l_ssn_middle.txt; pairs number: 5722
2017-08-18 11:49:54  task  INFO       rule: txt\3_fields_process_mrn\l_ssn_phone.txt; pairs number: 6670
2017-08-18 11:49:54  task  INFO       rule: txt\3_fields_process_mrn\l_dob_addr.txt; pairs number: 26790
2017-08-18 11:50:11  task  INFO       rule: txt\3_fields_process_mrn\l_addr_middle.txt; pairs number: 6080
2017-08-18 11:50:17  task  INFO       rule: txt\3_fields_process_mrn\l_middle_phone.txt; pairs number: 10712
2017-08-18 11:50:28  task  INFO       rule: txt\3_fields_process_mrn\dob_ssn_middle.txt; pairs number: 6068
2017-08-18 11:50:34  task  INFO       rule: txt\3_fields_process_mrn\dob_ssn_addr.txt; pairs number: 12072
2017-08-18 11:50:53  task  INFO       rule: txt\3_fields_process_mrn\l_addr_phone.txt; pairs number: 15542
2017-08-18 11:50:57  task  INFO       rule: txt\3_fields_process_mrn\dob_addr_phone.txt; pairs number: 14618
2017-08-18 11:50:59  task  INFO       rule: txt\3_fields_process_mrn\dob_ssn_phone.txt; pairs number: 6758
2017-08-18 11:51:04  task  INFO       rule: txt\3_fields_process_mrn\ssn_addr_phone.txt; pairs number: 2396
2017-08-18 11:51:06  task  INFO       rule: txt\3_fields_process_mrn\l_dob_phone.txt; pairs number: 48336
2017-08-19 15:59:07  task  INFO       rule: txt\3_fields_process_alternative\l_dob_middle.txt; pairs number: 17870
2017-08-19 15:59:13  task  INFO       rule: txt\3_fields_process_alternative\l_dob_addr.txt; pairs number: 26790
2017-08-19 15:59:18  task  INFO       rule: txt\3_fields_process_alternative\l_dob_email.txt; pairs number: 42
2017-08-19 15:59:38  task  INFO       rule: txt\3_fields_process_alternative\l_dob_ssn.txt; pairs number: 33216
2017-08-19 16:00:06  task  INFO       rule: txt\3_fields_process_alternative\l_dob_gender.txt; pairs number: 84238
2017-08-19 16:00:09  task  INFO       rule: txt\3_fields_process_alternative\l_gender_ssn.txt; pairs number: 28426
2017-08-19 16:00:21  task  INFO       rule: txt\3_fields_process_alternative\l_dob_phone.txt; pairs number: 48336
2017-08-19 16:00:47  task  INFO       rule: txt\3_fields_process_alternative\l_ssn_addr.txt; pairs number: 11146
2017-08-19 16:00:59  task  INFO       rule: txt\3_fields_process_alternative\l_gender_phone.txt; pairs number: 49428
2017-08-19 16:01:00  task  INFO       rule: txt\3_fields_process_alternative\l_ssn_phone.txt; pairs number: 6670
2017-08-19 16:01:07  task  INFO       rule: txt\3_fields_process_alternative\l_ssn_email.txt; pairs number: 0
2017-08-19 16:01:14  task  INFO       rule: txt\3_fields_process_alternative\l_gender_addr.txt; pairs number: 55394
2017-08-19 16:01:17  task  INFO       rule: txt\3_fields_process_alternative\l_middle_ssn.txt; pairs number: 5722
2017-08-19 16:01:24  task  INFO       rule: txt\3_fields_process_alternative\l_middle_email.txt; pairs number: 898
2017-08-19 16:01:30  task  INFO       rule: txt\3_fields_process_alternative\l_middle_phone.txt; pairs number: 10712
2017-08-19 16:01:37  task  INFO       rule: txt\3_fields_process_alternative\l_phone_email.txt; pairs number: 0
2017-08-19 16:01:38  task  INFO       rule: txt\3_fields_process_alternative\l_middle_addr.txt; pairs number: 6080
2017-08-19 16:01:46  task  INFO       rule: txt\3_fields_process_alternative\l_addr_email.txt; pairs number: 170
2017-08-19 16:02:10  task  INFO       rule: txt\3_fields_process_alternative\l_addr_phone.txt; pairs number: 15542
2017-08-19 16:02:17  task  INFO       rule: txt\3_fields_process_alternative\dob_gender_middle.txt; pairs number: 35758
2017-08-19 16:02:32  task  INFO       rule: txt\3_fields_process_alternative\dob_gender_ssn.txt; pairs number: 32220
2017-08-19 16:02:37  task  INFO       rule: txt\3_fields_process_alternative\dob_gender_email.txt; pairs number: 246
2017-08-19 16:02:47  task  INFO       rule: txt\3_fields_process_alternative\dob_middle_ssn.txt; pairs number: 6068
2017-08-19 16:03:09  task  INFO       rule: txt\3_fields_process_alternative\dob_middle_addr.txt; pairs number: 5894
2017-08-19 16:03:18  task  INFO       rule: txt\3_fields_process_alternative\dob_gender_phone.txt; pairs number: 47360
2017-08-19 16:03:19  task  INFO       rule: txt\3_fields_process_alternative\dob_gender_addr.txt; pairs number: 27820
2017-08-19 16:03:25  task  INFO       rule: txt\3_fields_process_alternative\dob_middle_email.txt; pairs number: 0
2017-08-19 16:03:36  task  INFO       rule: txt\3_fields_process_alternative\dob_middle_phone.txt; pairs number: 10522
2017-08-19 16:03:42  task  INFO       rule: txt\3_fields_process_alternative\dob_ssn_email.txt; pairs number: 0
2017-08-19 16:03:46  task  INFO       rule: txt\3_fields_process_alternative\dob_ssn_addr.txt; pairs number: 12072
2017-08-19 16:03:54  task  INFO       rule: txt\3_fields_process_alternative\dob_addr_email.txt; pairs number: 0
2017-08-19 16:04:02  task  INFO       rule: txt\3_fields_process_alternative\dob_phone_email.txt; pairs number: 0
2017-08-19 16:04:05  task  INFO       rule: txt\3_fields_process_alternative\dob_ssn_phone.txt; pairs number: 6758
2017-08-19 16:04:17  task  INFO       rule: txt\3_fields_process_alternative\gender_ssn_addr.txt; pairs number: 10252
2017-08-19 16:04:22  task  INFO       rule: txt\3_fields_process_alternative\gender_ssn_email.txt; pairs number: 0
2017-08-19 16:04:31  task  INFO       rule: txt\3_fields_process_alternative\gender_ssn_phone.txt; pairs number: 6816
2017-08-19 16:04:34  task  INFO       rule: txt\3_fields_process_alternative\dob_addr_phone.txt; pairs number: 14618
2017-08-19 16:04:42  task  INFO       rule: txt\3_fields_process_alternative\middle_ssn_phone.txt; pairs number: 930
2017-08-19 16:04:46  task  INFO       rule: txt\3_fields_process_alternative\middle_ssn_addr.txt; pairs number: 2032
2017-08-19 16:04:48  task  INFO       rule: txt\3_fields_process_alternative\middle_ssn_email.txt; pairs number: 0
2017-08-19 16:04:56  task  INFO       rule: txt\3_fields_process_alternative\middle_addr_email.txt; pairs number: 0
2017-08-19 16:05:01  task  INFO       rule: txt\3_fields_process_alternative\middle_phone_email.txt; pairs number: 0
2017-08-19 16:05:11  task  INFO       rule: txt\3_fields_process_alternative\ssn_addr_phone.txt; pairs number: 2396
2017-08-19 16:05:16  task  INFO       rule: txt\3_fields_process_alternative\ssn_addr_email.txt; pairs number: 0
2017-08-19 16:05:22  task  INFO       rule: txt\3_fields_process_alternative\middle_addr_phone.txt; pairs number: 3272
2017-08-19 16:05:22  task  INFO       rule: txt\3_fields_process_alternative\ssn_phone_email.txt; pairs number: 0
2017-08-19 16:05:26  task  INFO       rule: txt\3_fields_process_alternative\addr_phone_email.txt; pairs number: 0
2017-08-19 16:05:35  task  INFO       rule: txt\3_fields_process_alternative\gender_addr_phone.txt; pairs number: 15288
2017-08-19 16:08:13  task  INFO       rule: txt\3_fields_process_alternative\l_gender_middle.txt; pairs number: 415650
2017-08-19 23:07:52  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175cda90 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:07:52  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175cdbe0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:07:52  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175d3208 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:07:53  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175d3ef0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:07:53  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175d3dd8 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:07:53  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175d3ba8 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:07:54  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175d3470 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:07:54  concurrent.futures ERROR      exception calling callback for <Future at 0x22c16edeac8 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:07:55  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175de0f0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:07:57  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175de320 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:07:57  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175de278 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:07:58  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175de3c8 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:07:59  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175de470 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:01  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175de5c0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:01  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175de518 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:03  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175de668 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:04  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175de710 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:07  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175de7b8 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:07  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175de860 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:08  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175de908 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:10  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175de9b0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:12  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175dea58 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:13  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175deb00 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:16  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175dec50 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:16  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175deba8 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:20  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175decf8 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:22  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175deda0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:24  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175dee48 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:25  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175deef0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:28  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175def98 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:30  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb080 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:34  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb128 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:34  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb1d0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:40  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb278 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:40  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb320 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:45  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb3c8 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:45  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb470 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:51  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb518 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:51  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb5c0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:56  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb668 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:08:56  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb710 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:03  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb7b8 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:04  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb860 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:09  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb908 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:10  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fb9b0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:16  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fba58 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:17  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fbb00 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:24  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fbba8 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:24  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fbc50 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:31  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fbcf8 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:32  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fbda0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:40  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fbe48 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:40  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fbef0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:48  concurrent.futures ERROR      exception calling callback for <Future at 0x22c175fbf98 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:48  concurrent.futures ERROR      exception calling callback for <Future at 0x22c17608080 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:58  concurrent.futures ERROR      exception calling callback for <Future at 0x22c17608128 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:09:58  concurrent.futures ERROR      exception calling callback for <Future at 0x22c176081d0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:10:05  concurrent.futures ERROR      exception calling callback for <Future at 0x22c17608278 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:10:05  concurrent.futures ERROR      exception calling callback for <Future at 0x22c17608320 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn) > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:10:17  concurrent.futures ERROR      exception calling callback for <Future at 0x22c176083c8 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn, "w") > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:10:17  concurrent.futures ERROR      exception calling callback for <Future at 0x22c17608470 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn, "w") > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:10:20  concurrent.futures ERROR      exception calling callback for <Future at 0x22c176085c0 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn, "w") > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
2017-08-19 23:10:20  concurrent.futures ERROR      exception calling callback for <Future at 0x22c17608518 state=finished raised TypeError>
Traceback (most recent call last):
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "process_name_alternative_spelling.py", line 21, in output_matched_result
    pairs = future.result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "D:\anacoda\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "D:\anacoda\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "process_name_alternative_spelling.py", line 63, in process_alternative_name
    if measure_ssn_similarity(f_ssn, s_ssn, "w") > 0.95:
TypeError: measure_ssn_similarity() missing 1 required positional argument: 'sign'
